### ISSUE TITLE
Failing to load rome.properties

### ISSUE THREAD

**Issue by PatrickGotthard** [rometools/rome#130] opened 2013-09-30 15:42 UTC
<pre>=== This issue was migrated from JIRA ===
Type: Bug
Priority: Major
Status: Open
Resolution: UNRESOLVED
Reported by: buckett
Assigned to: ROME Jira Lead
Created: Mon Apr 20 10:47:11 CEST 2009
Updated: Thu Sep 15 20:55:38 CEST 2011
Resolved: Mon Apr 20 13:29:19 CEST 2009
Version: current
Fix version: milestone 1
JIRA Link: <a href="https://rometools.jira.com/browse/ROME-129">https://rometools.jira.com/browse/ROME-129</a>
=========================================</pre>
<p>Currently we use an old version of rome, rome&#45;fetcher in Sakai<br class="atl-forced-newline" /> (<a href="http://sakaiproject.org" class="external-link" rel="nofollow">http://sakaiproject.org</a>) and I was looking as upgrading them to the latest<br class="atl-forced-newline" /> version to them. Currently Sakai has complicated classloader setup. There is a<br class="atl-forced-newline" /> description of it here.<br class="atl-forced-newline" /> <br class="atl-forced-newline" /> <a href="https://source.sakaiproject.org/svn/reference/trunk/docs/architecture/sakai_component.doc" class="external-link" rel="nofollow">https://source.sakaiproject.org/svn/reference/trunk/docs/architecture/sakai&#95;component.doc</a><br class="atl-forced-newline" /> <br class="atl-forced-newline" /> Sakai runs ontop of tomcat and each "component" has it's own classloader that<br class="atl-forced-newline" /> child of the shared classloader. The API for the component goes in shared so<br class="atl-forced-newline" /> that both the component and any webapp can access. The component then implements<br class="atl-forced-newline" /> this APi. But the implementation code  can't be accessed by the webapp as the<br class="atl-forced-newline" /> component's classloader isn't a parent of the webapps. This prevents any webapps<br class="atl-forced-newline" /> accessing anything in a component.<br class="atl-forced-newline" /> <br class="atl-forced-newline" /> Currently there is an API for getting RSS feeds which is implemented by a<br class="atl-forced-newline" /> component containing rome. The problem is that when a webapp calls through to<br class="atl-forced-newline" /> this component the thread classloader is still set to the webapp's so it<br class="atl-forced-newline" /> attempts to load the master configuration file (rome.properties) from the<br class="atl-forced-newline" /> webapp. This fails and causes rome to stop working.<br class="atl-forced-newline" /> <br class="atl-forced-newline" /> It would be useful if PropertiesLoader could use either the thread classloader<br class="atl-forced-newline" /> or the classloader that loaded PropertiesLoader to load the configuration.</p>

**Comment by lewismc** [comment] 2015-01-16 15:12
Is anyone thinking about testing this patch out?

**Comment by sebastian-nagel** [comment] 2015-01-27 21:22
This problem is also hit by Apache Nutch (cf. [NUTCH-1494](https://issues.apache.org/jira/browse/NUTCH-1494)  and  [NUTCH-1893](https://issues.apache.org/jira/browse/NUTCH-1893)): various documents formats (including feeds) are parsed by plugins, every plugin has its own class loader. The problem is currently worked around by downgrading to rome 0.9.

**Comment by buckett** [comment] 2015-09-16 17:15
Is there anything that needs doing to get this fix into rome? If I created a pull request would that help?

**Comment by mishako** [comment] 2015-12-20 13:58
@lewismc @sebastian-nagel @buckett 
This seems to have been fixed since Rome `1.5.0`, i.e. calls to `Thread.currentThread().getContextClassLoader()` have been removed in https://github.com/rometools/rome/commit/6029420e5f7eea32cecd3cf6c504459da0bc8d77. The class loader used in Rome now is the one that loaded Rome classes and has access to `rome.properties`.

However you might have problems using Rome in OSGi environment because it's not being packaged as an OSGi bundle. This will be addressed in OSGi-related issues like #143 and #135.

**Comment by sebastian-nagel** [comment] 2016-01-04 18:49
@mishako @lewismc I can confirm that the problem is fixed when Rome 1.5.1 is used (I didn't test 1.5.0). We are going to upgrade the Rome library dependency, see [NUTCH-2193](https://issues.apache.org/jira/browse/NUTCH-2193). Thanks!

**Closed** 2016-01-05 19:09 UTC
Labels: bug, classpath/OSGI
