### ISSUE TITLE
remove dependencies on EOL projects

### ISSUE THREAD

**Issue by mschipperheyn** [rometools/rome#200] opened 2015-02-05 14:07 UTC
Rome seems to be using a number of EOL projects that are no longer being maintained. Things like httpclient 3.x and jdom 1. I'm trying to eliminate this old s*** from my project. Could you guys please upgrade to current version modules?

**Comment by PatrickGotthard** [comment] 2015-02-21 05:58
Duplicate of #197 and #198

**Closed by PatrickGotthard** 2015-02-21 05:58 UTC
Labels: duplicate
