### ISSUE TITLE
RSS channel's pubDate and lastBuildDate are mixed.

### ISSUE THREAD

**Issue by mishako** [rometools/rome#226] opened 2016-02-09 12:19 UTC
<a href="https://github.com/PatrickGotthard"><img src="https://avatars.githubusercontent.com/u/2995260?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [PatrickGotthard](https://github.com/PatrickGotthard)**
_Monday Sep 30, 2013 at 15:37 GMT_
_Originally opened as https://github.com/rometools/rome-fetcher/issues/4_

---

<pre>=== This issue was migrated from JIRA ===
Type: Bug
Priority: Major
Status: Open
Resolution: Unresolved
Environment: 1.0 version (of ROME Fetcher)
Reported by: Vlastimil Fürst
Assigned to: Nick Lothian
Created: Fri Jun 28 15:47:43 CEST 2013
Updated: Fri Jun 28 16:15:11 CEST 2013
JIRA Link: <a href="https://rometools.jira.com/browse/FETCHER-3">https://rometools.jira.com/browse/FETCHER-3</a>
=========================================</pre>

<p>In com.sun.syndication.feed.rss.Channel :<br/>
getLastBuildDate() always seem to return null;<br/>
getPubDate() returns pubDate correctly, but if pubDate tag isn't present in the RSS feed, content of lastBuildDate tag is returned instead.</p>

<p>This implies that in case both pubDate and lastBuildDate tags are filled, the contents of lastBuildDate can't be retrieved. In case only lastBuildDate is present, it can be read, but it's wrongly interpreted as pubDate.</p>

**Comment by mishako** [comment] 2016-02-09 12:19
<a href="https://github.com/PatrickGotthard"><img src="https://avatars.githubusercontent.com/u/2995260?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [PatrickGotthard](https://github.com/PatrickGotthard)**
_Monday Sep 30, 2013 at 15:37 GMT_

----

<pre>=== This comment was migrated from JIRA ===
Author: vlasec
Created: Fri Jun 28 16:13:12 CEST 2013
===========================================</pre>
<p>Just in case it helps, the feed itself it's obtained this way:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
fetchData(java.net.URL feedUrl; <span class="code-comment">//contains the URL, passed as parameter
</span>com.sun.syndication.io.SyndFeedInput input = <span class="code-keyword">new</span> c.s.s.i.SyndFeedInput();
com.sun.syndication.io.XmlReader reader = <span class="code-keyword">new</span> c.s.s.i.XmlReader(feedUrl);
com.sun.syndication.feed.synd.SyndFeed feed = input.build(reader);
<span class="code-comment">// intermezzo where we decide <span class="code-keyword">if</span> it's RSS or Atom and call the right processor, then:
</span><span class="code-keyword">if</span> (!(feed <span class="code-keyword">instanceof</span> com.sun.syndication.feed.rss.Channel)) {
  <span class="code-comment">// <span class="code-keyword">throw</span> some exception
</span>}
com.sun.syndication.feed.rss.Channel rss = (c.s.s.f.r.Channel) feed;
<span class="code-comment">// and then we read the contents and put it into our db structures.</span>
</pre>
</div></div>

<p>In case I'm doing something wrong, please tell me. It is a code I took from a colleague who was leaving for a bigger company.</p>

**Comment by PatrickGotthard** [comment] 2021-12-27 22:58
Closing this issue because rome-fetcher is deprecated an the issue is really old.

**Closed by PatrickGotthard** 2021-12-27 22:58 UTC
Labels: bug, wont-fix, rome-fetcher
