### ISSUE TITLE
DataParser parseUsingMask public

### ISSUE THREAD

**Issue by PatrickVanbrabant** [rometools/rome#427] opened 2019-05-14 09:42 UTC
Dear Team,

In the DateParser class the method parseUsingMask is private. I had to implement a specific WireFeedParser which has to parse dates using a specifc format mask.

But because this method is private I could not reusethat method.
Given that the method does not expose any internals of the class, I do not think it would harm any one if the method could become public,.

Many thanks for considering this option

Regards

Patrick

**Comment by lutzhorn** [comment] 2019-06-07 13:55
Couldn't you just set the mask as part of the property `datetime.extra.masks` and use `DateParser.parseDate(String, Locale)`? This method revert so `parseUsingMask` if the input can not be parsed using the W3C or RFC822 format.

**Comment by PatrickVanbrabant** [comment] 2019-06-07 14:28
That is exactly the problem. The pattern I need is the yyyyMMdd pattern
which matches with the yyyy pattern of w3c. But results in completely wrong
date

Op vr 7 jun. 2019 15:55 schreef Lutz Horn <notifications@github.com>:

**Comment by lutzhorn** [comment] 2019-06-07 14:32
Do you see the same behaviour as described in #423? I've added a PR for this issue.

**Comment by PatrickVanbrabant** [comment] 2019-06-07 17:13
Yes.

Op vr 7 jun. 2019 16:32 schreef Lutz Horn <notifications@github.com>:

**Comment by PatrickVanbrabant** [comment] 2019-06-07 17:23
But I do not agree that cystom formats should come first.

We are dealing with standards here. Standards describe some patterns. Rome
is adding to these strict patterns some relaxing patterns (like this yyyy).

I think the implementation should first try the strict patterns defined in
the respective standards, then look at the cystom patterns and as last step
try the relaxing patterns


Op vr 7 jun. 2019 19:12 schreef Patrick Vanbrabant <
patrick.vanbrabant@gmail.com>:

**Comment by lutzhorn** [comment] 2019-06-07 18:26
The problem is that `yyyy` machtes `20190627. Some day, this year will come. Years will not forever have only four digits. So it is impossible do determine if this input is a year or a year-month-day-combination.

**Comment by PatrickVanbrabant** [comment] 2019-06-07 18:32
Well I'm willing to take that risk.
I'm sure that by that day java won't be used anymore :))

Op vr 7 jun. 2019 20:26 schreef Lutz Horn <notifications@github.com>:

**Comment by mishako** [comment] 2019-06-09 20:26
I'm leaning towards "custom formats should come first" simply because it makes it easier for the user to configure the parser. Basically convenience above standards. I actually just merged #429 so I guess it resolves this issue. Haven't released a new version yet though, will do it in the next days.

**Closed** 2019-06-09 20:26 UTC
Labels: enhancement
